job:
  tags:
    general-docker

default:
    image: node:14

variables:
  GIT_STRATEGY: fetch
 
stages:
    - test

test:
    stage: test
    script:
        - npm -v
        - node -v
        - pwd
        - cd Frontend
        - pwd
        - npm ci
        - CI=true npm test 
