default:
    image: node:14
 
variables:
  GIT_STRATEGY: clone

stages:
    - test

test:
    tags: [general-docker]
    stage: test
    script:
        - npm set progress=false
        - cd Frontend
        - npm i mocha -g
        - npm run mocha-test
        - npm install
        - npm run mocha-test 
        - cd ../Backend
        - npm install
        - npm run test
