# image: node:11.10.1
 
# variables:
#   GIT_STRATEGY: clone

stages:
    - test
 
test:
    stage: test
    script:
        - cd Frontend
        - node -v
        - npm install
        - npm run test 
