image: node:14.15.0
 
variables:
  GIT_STRATEGY: clone

stages:
    - test
 
test:
    stage: test
    script:
        - cd Frontend
        - node -v
        - npm -v
        - npm install
        - npm run test 
