default:
    image: node:default
 
stages:
    - test

test:
    stage: test
    script:
        - npm -v
        - node -v
        - pwd
        - cd Frontend
        - pwd
        - npm ci
        - CI=true npm test 
