default:
    image: node:14

variables:
  GIT_STRATEGY: fetch
 
stages:
    - test

test:
    tags: [general-docker]
    stage: test
    script:
        - cd Frontend
        - npm i cypress -g
        - node -v
        - npm -v
        - npm install
        - npm run test 
