image: node:11.10.1
 
variables:
  GIT_STRATEGY: fetch

stages:
    - test
 
test:
    stage: test
    script:
        - cd Frontend
        - node -v
        - npm -v
        - npm install
        - npm run test 
